#! /bin/sh -e

target_dir=$1
if test -z "$1"; then
    echo "usage: onvif-wsdl2h target_dir"
    exit 1
fi

cd $target_dir
gsoap_prefix=`pkg-config --variable=prefix gsoap`
soapcpp2 -2 -C -I "$gsoap_prefix/share/gsoap" -j -x onvif.h
soapcpp2 -a -x -L -pwsdd -I "$gsoap_prefix/share/gsoap" "$gsoap_prefix/share/gsoap/import/wsdd5.h"
